/* soapClient.cpp
   Generated by gSOAP 2.8.39 for foxwelltech.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.39 2018-10-10 09:11:43 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ExecuteSoapJmsRPC(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__ExecuteSoapJmsRPC soap_tmp_ns1__ExecuteSoapJmsRPC;
	struct ns1__ExecuteSoapJmsRPCResponse *soap_tmp_ns1__ExecuteSoapJmsRPCResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!ExecuteSoapJmsRPC";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__ExecuteSoapJmsRPC(soap, &soap_tmp_ns1__ExecuteSoapJmsRPC);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ExecuteSoapJmsRPC(soap, &soap_tmp_ns1__ExecuteSoapJmsRPC, "ns1:ExecuteSoapJmsRPC", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ExecuteSoapJmsRPC(soap, &soap_tmp_ns1__ExecuteSoapJmsRPC, "ns1:ExecuteSoapJmsRPC", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__ExecuteSoapJmsRPCResponse = soap_get_ns1__ExecuteSoapJmsRPCResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__ExecuteSoapJmsRPCResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__ExecuteSoapJmsRPCResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__GetWSDL(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__GetWSDL soap_tmp_ns1__GetWSDL;
	struct ns1__GetWSDLResponse *soap_tmp_ns1__GetWSDLResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!GetWSDL";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__GetWSDL(soap, &soap_tmp_ns1__GetWSDL);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__GetWSDL(soap, &soap_tmp_ns1__GetWSDL, "ns1:GetWSDL", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__GetWSDL(soap, &soap_tmp_ns1__GetWSDL, "ns1:GetWSDL", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__GetWSDLResponse = soap_get_ns1__GetWSDLResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__GetWSDLResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__GetWSDLResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__jmsexample(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *arg1, char *arg2, char *&Collection)
{	struct ns1__jmsexample soap_tmp_ns1__jmsexample;
	struct ns1__jmsexampleResponse *soap_tmp_ns1__jmsexampleResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!jmsexample";
	soap_tmp_ns1__jmsexample.arg1 = arg1;
	soap_tmp_ns1__jmsexample.arg2 = arg2;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__jmsexample(soap, &soap_tmp_ns1__jmsexample);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__jmsexample(soap, &soap_tmp_ns1__jmsexample, "ns1:jmsexample", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__jmsexample(soap, &soap_tmp_ns1__jmsexample, "ns1:jmsexample", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__jmsexampleResponse = soap_get_ns1__jmsexampleResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__jmsexampleResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__jmsexampleResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ping(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__ping soap_tmp_ns1__ping;
	struct ns1__pingResponse *soap_tmp_ns1__pingResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!ping";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__ping(soap, &soap_tmp_ns1__ping);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ping(soap, &soap_tmp_ns1__ping, "ns1:ping", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ping(soap, &soap_tmp_ns1__ping, "ns1:ping", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__pingResponse = soap_get_ns1__pingResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__pingResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__pingResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getPbomLinkByPartNumber(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__getPbomLinkByPartNumber soap_tmp_ns1__getPbomLinkByPartNumber;
	struct ns1__getPbomLinkByPartNumberResponse *soap_tmp_ns1__getPbomLinkByPartNumberResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!getPbomLinkByPartNumber";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__getPbomLinkByPartNumber(soap, &soap_tmp_ns1__getPbomLinkByPartNumber);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getPbomLinkByPartNumber(soap, &soap_tmp_ns1__getPbomLinkByPartNumber, "ns1:getPbomLinkByPartNumber", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getPbomLinkByPartNumber(soap, &soap_tmp_ns1__getPbomLinkByPartNumber, "ns1:getPbomLinkByPartNumber", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getPbomLinkByPartNumberResponse = soap_get_ns1__getPbomLinkByPartNumberResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__getPbomLinkByPartNumberResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__getPbomLinkByPartNumberResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__saveordertowc(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__saveordertowc soap_tmp_ns1__saveordertowc;
	struct ns1__saveordertowcResponse *soap_tmp_ns1__saveordertowcResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!saveordertowc";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__saveordertowc(soap, &soap_tmp_ns1__saveordertowc);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__saveordertowc(soap, &soap_tmp_ns1__saveordertowc, "ns1:saveordertowc", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__saveordertowc(soap, &soap_tmp_ns1__saveordertowc, "ns1:saveordertowc", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__saveordertowcResponse = soap_get_ns1__saveordertowcResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__saveordertowcResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__saveordertowcResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getorderbyoid(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__getorderbyoid soap_tmp_ns1__getorderbyoid;
	struct ns1__getorderbyoidResponse *soap_tmp_ns1__getorderbyoidResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!getorderbyoid";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__getorderbyoid(soap, &soap_tmp_ns1__getorderbyoid);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getorderbyoid(soap, &soap_tmp_ns1__getorderbyoid, "ns1:getorderbyoid", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getorderbyoid(soap, &soap_tmp_ns1__getorderbyoid, "ns1:getorderbyoid", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getorderbyoidResponse = soap_get_ns1__getorderbyoidResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__getorderbyoidResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__getorderbyoidResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getPbomEndPartByPartNumber(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__getPbomEndPartByPartNumber soap_tmp_ns1__getPbomEndPartByPartNumber;
	struct ns1__getPbomEndPartByPartNumberResponse *soap_tmp_ns1__getPbomEndPartByPartNumberResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!getPbomEndPartByPartNumber";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__getPbomEndPartByPartNumber(soap, &soap_tmp_ns1__getPbomEndPartByPartNumber);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getPbomEndPartByPartNumber(soap, &soap_tmp_ns1__getPbomEndPartByPartNumber, "ns1:getPbomEndPartByPartNumber", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getPbomEndPartByPartNumber(soap, &soap_tmp_ns1__getPbomEndPartByPartNumber, "ns1:getPbomEndPartByPartNumber", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getPbomEndPartByPartNumberResponse = soap_get_ns1__getPbomEndPartByPartNumberResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__getPbomEndPartByPartNumberResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__getPbomEndPartByPartNumberResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getPbomOriginalItemByPartNumber(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__getPbomOriginalItemByPartNumber soap_tmp_ns1__getPbomOriginalItemByPartNumber;
	struct ns1__getPbomOriginalItemByPartNumberResponse *soap_tmp_ns1__getPbomOriginalItemByPartNumberResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!getPbomOriginalItemByPartNumber";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__getPbomOriginalItemByPartNumber(soap, &soap_tmp_ns1__getPbomOriginalItemByPartNumber);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getPbomOriginalItemByPartNumber(soap, &soap_tmp_ns1__getPbomOriginalItemByPartNumber, "ns1:getPbomOriginalItemByPartNumber", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getPbomOriginalItemByPartNumber(soap, &soap_tmp_ns1__getPbomOriginalItemByPartNumber, "ns1:getPbomOriginalItemByPartNumber", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getPbomOriginalItemByPartNumberResponse = soap_get_ns1__getPbomOriginalItemByPartNumberResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__getPbomOriginalItemByPartNumberResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__getPbomOriginalItemByPartNumberResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__savechangeordertowc(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__savechangeordertowc soap_tmp_ns1__savechangeordertowc;
	struct ns1__savechangeordertowcResponse *soap_tmp_ns1__savechangeordertowcResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!savechangeordertowc";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__savechangeordertowc(soap, &soap_tmp_ns1__savechangeordertowc);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__savechangeordertowc(soap, &soap_tmp_ns1__savechangeordertowc, "ns1:savechangeordertowc", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__savechangeordertowc(soap, &soap_tmp_ns1__savechangeordertowc, "ns1:savechangeordertowc", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__savechangeordertowcResponse = soap_get_ns1__savechangeordertowcResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__savechangeordertowcResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__savechangeordertowcResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__fuZhuJianSelector(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__fuZhuJianSelector soap_tmp_ns1__fuZhuJianSelector;
	struct ns1__fuZhuJianSelectorResponse *soap_tmp_ns1__fuZhuJianSelectorResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!fuZhuJianSelector";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__fuZhuJianSelector(soap, &soap_tmp_ns1__fuZhuJianSelector);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__fuZhuJianSelector(soap, &soap_tmp_ns1__fuZhuJianSelector, "ns1:fuZhuJianSelector", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__fuZhuJianSelector(soap, &soap_tmp_ns1__fuZhuJianSelector, "ns1:fuZhuJianSelector", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__fuZhuJianSelectorResponse = soap_get_ns1__fuZhuJianSelectorResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__fuZhuJianSelectorResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__fuZhuJianSelectorResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__gongliangjiajuSelector(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__gongliangjiajuSelector soap_tmp_ns1__gongliangjiajuSelector;
	struct ns1__gongliangjiajuSelectorResponse *soap_tmp_ns1__gongliangjiajuSelectorResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!gongliangjiajuSelector";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__gongliangjiajuSelector(soap, &soap_tmp_ns1__gongliangjiajuSelector);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__gongliangjiajuSelector(soap, &soap_tmp_ns1__gongliangjiajuSelector, "ns1:gongliangjiajuSelector", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__gongliangjiajuSelector(soap, &soap_tmp_ns1__gongliangjiajuSelector, "ns1:gongliangjiajuSelector", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__gongliangjiajuSelectorResponse = soap_get_ns1__gongliangjiajuSelectorResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__gongliangjiajuSelectorResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__gongliangjiajuSelectorResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__gongZhuangSelector(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__gongZhuangSelector soap_tmp_ns1__gongZhuangSelector;
	struct ns1__gongZhuangSelectorResponse *soap_tmp_ns1__gongZhuangSelectorResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!gongZhuangSelector";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__gongZhuangSelector(soap, &soap_tmp_ns1__gongZhuangSelector);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__gongZhuangSelector(soap, &soap_tmp_ns1__gongZhuangSelector, "ns1:gongZhuangSelector", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__gongZhuangSelector(soap, &soap_tmp_ns1__gongZhuangSelector, "ns1:gongZhuangSelector", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__gongZhuangSelectorResponse = soap_get_ns1__gongZhuangSelectorResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__gongZhuangSelectorResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__gongZhuangSelectorResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__loadAssemblePartsByPartNumber(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__loadAssemblePartsByPartNumber soap_tmp_ns1__loadAssemblePartsByPartNumber;
	struct ns1__loadAssemblePartsByPartNumberResponse *soap_tmp_ns1__loadAssemblePartsByPartNumberResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!loadAssemblePartsByPartNumber";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__loadAssemblePartsByPartNumber(soap, &soap_tmp_ns1__loadAssemblePartsByPartNumber);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__loadAssemblePartsByPartNumber(soap, &soap_tmp_ns1__loadAssemblePartsByPartNumber, "ns1:loadAssemblePartsByPartNumber", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__loadAssemblePartsByPartNumber(soap, &soap_tmp_ns1__loadAssemblePartsByPartNumber, "ns1:loadAssemblePartsByPartNumber", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__loadAssemblePartsByPartNumberResponse = soap_get_ns1__loadAssemblePartsByPartNumberResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__loadAssemblePartsByPartNumberResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__loadAssemblePartsByPartNumberResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__sheBeiSelector(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__sheBeiSelector soap_tmp_ns1__sheBeiSelector;
	struct ns1__sheBeiSelectorResponse *soap_tmp_ns1__sheBeiSelectorResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!sheBeiSelector";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__sheBeiSelector(soap, &soap_tmp_ns1__sheBeiSelector);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__sheBeiSelector(soap, &soap_tmp_ns1__sheBeiSelector, "ns1:sheBeiSelector", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__sheBeiSelector(soap, &soap_tmp_ns1__sheBeiSelector, "ns1:sheBeiSelector", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__sheBeiSelectorResponse = soap_get_ns1__sheBeiSelectorResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__sheBeiSelectorResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__sheBeiSelectorResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__lingZuJianSelector(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__lingZuJianSelector soap_tmp_ns1__lingZuJianSelector;
	struct ns1__lingZuJianSelectorResponse *soap_tmp_ns1__lingZuJianSelectorResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!lingZuJianSelector";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__lingZuJianSelector(soap, &soap_tmp_ns1__lingZuJianSelector);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__lingZuJianSelector(soap, &soap_tmp_ns1__lingZuJianSelector, "ns1:lingZuJianSelector", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__lingZuJianSelector(soap, &soap_tmp_ns1__lingZuJianSelector, "ns1:lingZuJianSelector", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__lingZuJianSelectorResponse = soap_get_ns1__lingZuJianSelectorResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__lingZuJianSelectorResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__lingZuJianSelectorResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getorderbynumber(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__getorderbynumber soap_tmp_ns1__getorderbynumber;
	struct ns1__getorderbynumberResponse *soap_tmp_ns1__getorderbynumberResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!getorderbynumber";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__getorderbynumber(soap, &soap_tmp_ns1__getorderbynumber);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getorderbynumber(soap, &soap_tmp_ns1__getorderbynumber, "ns1:getorderbynumber", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getorderbynumber(soap, &soap_tmp_ns1__getorderbynumber, "ns1:getorderbynumber", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getorderbynumberResponse = soap_get_ns1__getorderbynumberResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__getorderbynumberResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__getorderbynumberResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__tipicalCraftSelector(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__tipicalCraftSelector soap_tmp_ns1__tipicalCraftSelector;
	struct ns1__tipicalCraftSelectorResponse *soap_tmp_ns1__tipicalCraftSelectorResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!tipicalCraftSelector";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__tipicalCraftSelector(soap, &soap_tmp_ns1__tipicalCraftSelector);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__tipicalCraftSelector(soap, &soap_tmp_ns1__tipicalCraftSelector, "ns1:tipicalCraftSelector", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__tipicalCraftSelector(soap, &soap_tmp_ns1__tipicalCraftSelector, "ns1:tipicalCraftSelector", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__tipicalCraftSelectorResponse = soap_get_ns1__tipicalCraftSelectorResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__tipicalCraftSelectorResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__tipicalCraftSelectorResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__reviseAndCheckOut(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *partNumber, char *&Collection)
{	struct ns1__reviseAndCheckOut soap_tmp_ns1__reviseAndCheckOut;
	struct ns1__reviseAndCheckOutResponse *soap_tmp_ns1__reviseAndCheckOutResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!reviseAndCheckOut";
	soap_tmp_ns1__reviseAndCheckOut.partNumber = partNumber;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__reviseAndCheckOut(soap, &soap_tmp_ns1__reviseAndCheckOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__reviseAndCheckOut(soap, &soap_tmp_ns1__reviseAndCheckOut, "ns1:reviseAndCheckOut", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__reviseAndCheckOut(soap, &soap_tmp_ns1__reviseAndCheckOut, "ns1:reviseAndCheckOut", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__reviseAndCheckOutResponse = soap_get_ns1__reviseAndCheckOutResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__reviseAndCheckOutResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__reviseAndCheckOutResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getZip(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *partNumber, char *&Collection)
{	struct ns1__getZip soap_tmp_ns1__getZip;
	struct ns1__getZipResponse *soap_tmp_ns1__getZipResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!getZip";
	soap_tmp_ns1__getZip.partNumber = partNumber;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__getZip(soap, &soap_tmp_ns1__getZip);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getZip(soap, &soap_tmp_ns1__getZip, "ns1:getZip", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getZip(soap, &soap_tmp_ns1__getZip, "ns1:getZip", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getZipResponse = soap_get_ns1__getZipResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__getZipResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__getZipResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getFolder(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *param, char *&Collection)
{	struct ns1__getFolder soap_tmp_ns1__getFolder;
	struct ns1__getFolderResponse *soap_tmp_ns1__getFolderResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!getFolder";
	soap_tmp_ns1__getFolder.param = param;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__getFolder(soap, &soap_tmp_ns1__getFolder);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getFolder(soap, &soap_tmp_ns1__getFolder, "ns1:getFolder", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getFolder(soap, &soap_tmp_ns1__getFolder, "ns1:getFolder", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getFolderResponse = soap_get_ns1__getFolderResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__getFolderResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__getFolderResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__callSearch(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *partNumber, char *&Collection)
{	struct ns1__callSearch soap_tmp_ns1__callSearch;
	struct ns1__callSearchResponse *soap_tmp_ns1__callSearchResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!callSearch";
	soap_tmp_ns1__callSearch.partNumber = partNumber;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__callSearch(soap, &soap_tmp_ns1__callSearch);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__callSearch(soap, &soap_tmp_ns1__callSearch, "ns1:callSearch", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__callSearch(soap, &soap_tmp_ns1__callSearch, "ns1:callSearch", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__callSearchResponse = soap_get_ns1__callSearchResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__callSearchResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__callSearchResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__callCheckUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *filePath, char *&Collection)
{	struct ns1__callCheckUser soap_tmp_ns1__callCheckUser;
	struct ns1__callCheckUserResponse *soap_tmp_ns1__callCheckUserResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!callCheckUser";
	soap_tmp_ns1__callCheckUser.filePath = filePath;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__callCheckUser(soap, &soap_tmp_ns1__callCheckUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__callCheckUser(soap, &soap_tmp_ns1__callCheckUser, "ns1:callCheckUser", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__callCheckUser(soap, &soap_tmp_ns1__callCheckUser, "ns1:callCheckUser", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__callCheckUserResponse = soap_get_ns1__callCheckUserResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__callCheckUserResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__callCheckUserResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__callCheckOut(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *partNumber, char *&Collection)
{	struct ns1__callCheckOut soap_tmp_ns1__callCheckOut;
	struct ns1__callCheckOutResponse *soap_tmp_ns1__callCheckOutResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!callCheckOut";
	soap_tmp_ns1__callCheckOut.partNumber = partNumber;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__callCheckOut(soap, &soap_tmp_ns1__callCheckOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__callCheckOut(soap, &soap_tmp_ns1__callCheckOut, "ns1:callCheckOut", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__callCheckOut(soap, &soap_tmp_ns1__callCheckOut, "ns1:callCheckOut", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__callCheckOutResponse = soap_get_ns1__callCheckOutResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__callCheckOutResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__callCheckOutResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__callCheckIn(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *filePath, char *&Collection)
{	struct ns1__callCheckIn soap_tmp_ns1__callCheckIn;
	struct ns1__callCheckInResponse *soap_tmp_ns1__callCheckInResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!callCheckIn";
	soap_tmp_ns1__callCheckIn.filePath = filePath;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__callCheckIn(soap, &soap_tmp_ns1__callCheckIn);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__callCheckIn(soap, &soap_tmp_ns1__callCheckIn, "ns1:callCheckIn", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__callCheckIn(soap, &soap_tmp_ns1__callCheckIn, "ns1:callCheckIn", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__callCheckInResponse = soap_get_ns1__callCheckInResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__callCheckInResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__callCheckInResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__callProduct(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__callProduct soap_tmp_ns1__callProduct;
	struct ns1__callProductResponse *soap_tmp_ns1__callProductResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!callProduct";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__callProduct(soap, &soap_tmp_ns1__callProduct);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__callProduct(soap, &soap_tmp_ns1__callProduct, "ns1:callProduct", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__callProduct(soap, &soap_tmp_ns1__callProduct, "ns1:callProduct", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__callProductResponse = soap_get_ns1__callProductResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__callProductResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__callProductResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__unCheckOut(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *filePath, char *&Collection)
{	struct ns1__unCheckOut soap_tmp_ns1__unCheckOut;
	struct ns1__unCheckOutResponse *soap_tmp_ns1__unCheckOutResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!unCheckOut";
	soap_tmp_ns1__unCheckOut.filePath = filePath;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__unCheckOut(soap, &soap_tmp_ns1__unCheckOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__unCheckOut(soap, &soap_tmp_ns1__unCheckOut, "ns1:unCheckOut", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__unCheckOut(soap, &soap_tmp_ns1__unCheckOut, "ns1:unCheckOut", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__unCheckOutResponse = soap_get_ns1__unCheckOutResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__unCheckOutResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__unCheckOutResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getordercreatorbynumber(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__getordercreatorbynumber soap_tmp_ns1__getordercreatorbynumber;
	struct ns1__getordercreatorbynumberResponse *soap_tmp_ns1__getordercreatorbynumberResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!getordercreatorbynumber";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__getordercreatorbynumber(soap, &soap_tmp_ns1__getordercreatorbynumber);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getordercreatorbynumber(soap, &soap_tmp_ns1__getordercreatorbynumber, "ns1:getordercreatorbynumber", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getordercreatorbynumber(soap, &soap_tmp_ns1__getordercreatorbynumber, "ns1:getordercreatorbynumber", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getordercreatorbynumberResponse = soap_get_ns1__getordercreatorbynumberResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__getordercreatorbynumberResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__getordercreatorbynumberResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__pendingWork(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__pendingWork soap_tmp_ns1__pendingWork;
	struct ns1__pendingWorkResponse *soap_tmp_ns1__pendingWorkResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!pendingWork";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__pendingWork(soap, &soap_tmp_ns1__pendingWork);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__pendingWork(soap, &soap_tmp_ns1__pendingWork, "ns1:pendingWork", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__pendingWork(soap, &soap_tmp_ns1__pendingWork, "ns1:pendingWork", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__pendingWorkResponse = soap_get_ns1__pendingWorkResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__pendingWorkResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__pendingWorkResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__updateUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__updateUser soap_tmp_ns1__updateUser;
	struct ns1__updateUserResponse *soap_tmp_ns1__updateUserResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!updateUser";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__updateUser(soap, &soap_tmp_ns1__updateUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__updateUser(soap, &soap_tmp_ns1__updateUser, "ns1:updateUser", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__updateUser(soap, &soap_tmp_ns1__updateUser, "ns1:updateUser", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__updateUserResponse = soap_get_ns1__updateUserResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__updateUserResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__updateUserResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__checkLogin(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *&Collection)
{	struct ns1__checkLogin soap_tmp_ns1__checkLogin;
	struct ns1__checkLoginResponse *soap_tmp_ns1__checkLoginResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!checkLogin";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__checkLogin(soap, &soap_tmp_ns1__checkLogin);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__checkLogin(soap, &soap_tmp_ns1__checkLogin, "ns1:checkLogin", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__checkLogin(soap, &soap_tmp_ns1__checkLogin, "ns1:checkLogin", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__checkLoginResponse = soap_get_ns1__checkLoginResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__checkLoginResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__checkLoginResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getPartList(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *operType, char *partNumber, char *&Collection)
{	struct ns1__getPartList soap_tmp_ns1__getPartList;
	struct ns1__getPartListResponse *soap_tmp_ns1__getPartListResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!getPartList";
	soap_tmp_ns1__getPartList.operType = operType;
	soap_tmp_ns1__getPartList.partNumber = partNumber;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__getPartList(soap, &soap_tmp_ns1__getPartList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getPartList(soap, &soap_tmp_ns1__getPartList, "ns1:getPartList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getPartList(soap, &soap_tmp_ns1__getPartList, "ns1:getPartList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getPartListResponse = soap_get_ns1__getPartListResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__getPartListResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__getPartListResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getBom(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *operType, char *partNumber, char *&Collection)
{	struct ns1__getBom soap_tmp_ns1__getBom;
	struct ns1__getBomResponse *soap_tmp_ns1__getBomResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!getBom";
	soap_tmp_ns1__getBom.operType = operType;
	soap_tmp_ns1__getBom.partNumber = partNumber;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__getBom(soap, &soap_tmp_ns1__getBom);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getBom(soap, &soap_tmp_ns1__getBom, "ns1:getBom", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getBom(soap, &soap_tmp_ns1__getBom, "ns1:getBom", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getBomResponse = soap_get_ns1__getBomResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__getBomResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__getBomResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__checkInPbom(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *fileName, char *&Collection)
{	struct ns1__checkInPbom soap_tmp_ns1__checkInPbom;
	struct ns1__checkInPbomResponse *soap_tmp_ns1__checkInPbomResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!checkInPbom";
	soap_tmp_ns1__checkInPbom.fileName = fileName;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__checkInPbom(soap, &soap_tmp_ns1__checkInPbom);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__checkInPbom(soap, &soap_tmp_ns1__checkInPbom, "ns1:checkInPbom", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__checkInPbom(soap, &soap_tmp_ns1__checkInPbom, "ns1:checkInPbom", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__checkInPbomResponse = soap_get_ns1__checkInPbomResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__checkInPbomResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__checkInPbomResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__checkInDoc(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *operType, char *fileName, char *&Collection)
{	struct ns1__checkInDoc soap_tmp_ns1__checkInDoc;
	struct ns1__checkInDocResponse *soap_tmp_ns1__checkInDocResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!checkInDoc";
	soap_tmp_ns1__checkInDoc.operType = operType;
	soap_tmp_ns1__checkInDoc.fileName = fileName;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__checkInDoc(soap, &soap_tmp_ns1__checkInDoc);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__checkInDoc(soap, &soap_tmp_ns1__checkInDoc, "ns1:checkInDoc", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__checkInDoc(soap, &soap_tmp_ns1__checkInDoc, "ns1:checkInDoc", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__checkInDocResponse = soap_get_ns1__checkInDocResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__checkInDocResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__checkInDocResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getBOMOfHsf(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *operType, char *partNumber, char *&Collection)
{	struct ns1__getBOMOfHsf soap_tmp_ns1__getBOMOfHsf;
	struct ns1__getBOMOfHsfResponse *soap_tmp_ns1__getBOMOfHsfResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!getBOMOfHsf";
	soap_tmp_ns1__getBOMOfHsf.operType = operType;
	soap_tmp_ns1__getBOMOfHsf.partNumber = partNumber;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__getBOMOfHsf(soap, &soap_tmp_ns1__getBOMOfHsf);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getBOMOfHsf(soap, &soap_tmp_ns1__getBOMOfHsf, "ns1:getBOMOfHsf", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getBOMOfHsf(soap, &soap_tmp_ns1__getBOMOfHsf, "ns1:getBOMOfHsf", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getBOMOfHsfResponse = soap_get_ns1__getBOMOfHsfResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__getBOMOfHsfResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__getBOMOfHsfResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getDocInfoOfContent(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *operType, char *docNumber, char *&Collection)
{	struct ns1__getDocInfoOfContent soap_tmp_ns1__getDocInfoOfContent;
	struct ns1__getDocInfoOfContentResponse *soap_tmp_ns1__getDocInfoOfContentResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!getDocInfoOfContent";
	soap_tmp_ns1__getDocInfoOfContent.operType = operType;
	soap_tmp_ns1__getDocInfoOfContent.docNumber = docNumber;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__getDocInfoOfContent(soap, &soap_tmp_ns1__getDocInfoOfContent);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getDocInfoOfContent(soap, &soap_tmp_ns1__getDocInfoOfContent, "ns1:getDocInfoOfContent", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getDocInfoOfContent(soap, &soap_tmp_ns1__getDocInfoOfContent, "ns1:getDocInfoOfContent", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getDocInfoOfContentResponse = soap_get_ns1__getDocInfoOfContentResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__getDocInfoOfContentResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__getDocInfoOfContentResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getDocInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *operType, char *docNumber, char *&Collection)
{	struct ns1__getDocInfo soap_tmp_ns1__getDocInfo;
	struct ns1__getDocInfoResponse *soap_tmp_ns1__getDocInfoResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!getDocInfo";
	soap_tmp_ns1__getDocInfo.operType = operType;
	soap_tmp_ns1__getDocInfo.docNumber = docNumber;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__getDocInfo(soap, &soap_tmp_ns1__getDocInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getDocInfo(soap, &soap_tmp_ns1__getDocInfo, "ns1:getDocInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getDocInfo(soap, &soap_tmp_ns1__getDocInfo, "ns1:getDocInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getDocInfoResponse = soap_get_ns1__getDocInfoResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__getDocInfoResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__getDocInfoResponse->Collection;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__SearchResource(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *operType, char *resourceNumber, char *&Collection)
{	struct ns1__SearchResource soap_tmp_ns1__SearchResource;
	struct ns1__SearchResourceResponse *soap_tmp_ns1__SearchResourceResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plmtest.zhengfei.com/Windchill/servlet/RPC";
	if (soap_action == NULL)
		soap_action = "urn:ie-soap-rpc:com.infoengine.soap!SearchResource";
	soap_tmp_ns1__SearchResource.operType = operType;
	soap_tmp_ns1__SearchResource.resourceNumber = resourceNumber;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__SearchResource(soap, &soap_tmp_ns1__SearchResource);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SearchResource(soap, &soap_tmp_ns1__SearchResource, "ns1:SearchResource", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SearchResource(soap, &soap_tmp_ns1__SearchResource, "ns1:SearchResource", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	Collection = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__SearchResourceResponse = soap_get_ns1__SearchResourceResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__SearchResourceResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	Collection = soap_tmp_ns1__SearchResourceResponse->Collection;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
